<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm</name>
   <tag></tag>
   <elementGuidId>b2cbaab2-790e-4503-9d8b-01ba770a3b1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//input[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
