<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>code</name>
   <tag></tag>
   <elementGuidId>0f007490-a2f6-4bf6-8437-f4deb1bc1903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//pre[contains(@class,'CodeMirror-line')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
