<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>success</name>
   <tag></tag>
   <elementGuidId>98cd4a10-1b49-4b1c-b45d-b42951860869</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body//div[@id='js-flash-container']//div//div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
